blank_issues_enabled: false

issue_templates:
  - name: 🐛 Bug Report
    description: Signalez un bug ou un comportement inattendu
    labels: [bug]
    assignees: []
    body:
      - type: markdown
        attributes:
          value: |
            Merci de prendre le temps de signaler un bug !

      - type: input
        id: titre
        attributes:
          label: Titre clair du bug
          placeholder: Exemple : "Erreur lors de l'ouverture du menu"
        validations:
          required: true

      - type: textarea
        id: description
        attributes:
          label: Description du problème
          placeholder: Décrivez le comportement observé et attendu
        validations:
          required: true

      - type: dropdown
        id: environnement
        attributes:
          label: Environnement
          options:
            - Production
            - Développement
            - Local
          default: 0

      - type: textarea
        id: reproduction
        attributes:
          label: Étapes pour reproduire
          placeholder: |
            1. Aller à '...'
            2. Cliquer sur '....'
            3. Voir l'erreur

      - type: input
        id: version
        attributes:
          label: Version de l'application
          placeholder: Exemple : v1.2.3

  - name: 💡 Feature Request
    description: Proposez une nouvelle fonctionnalité ou amélioration
    labels: [enhancement]
    assignees: []
    body:
      - type: markdown
        attributes:
          value: |
            Merci de proposer une amélioration !

      - type: input
        id: feature-title
        attributes:
          label: Titre de la suggestion
          placeholder: Exemple : "Ajouter une option de thème sombre"
        validations:
          required: true

      - type: textarea
        id: contexte
        attributes:
          label: Contexte
          placeholder: Expliquez pourquoi cette fonctionnalité serait utile

      - type: textarea
        id: proposition
        attributes:
          label: Proposition détaillée
          placeholder: Expliquez comment vous voyez cette fonctionnalité fonctionner

